# config
cover: http://img.kbscript.com/bg_img.jpg
logo: /img/logo.svg
top_saying:
- title: YOU'VE MADE A <span>BRAVE</span> DECISION, WELCOME.
- content: 每一个不曾起舞的日子都是对生命的辜负。
bottom_saying: Lok’tar ogar
# Content
excerpt_link: Read More

rss: /atom.xml

highlightjs: vs

#Works
works:
- works_name: wechatPaySDK
  works_url: https://github.com/MrKou47/wechat-pay-sdk
- works_name: qiyuSDK
  works_url: https://github.com/MrKou47/qiyu-sdk
- works_name: PainterOnline
  works_url: https://github.com/MrKou47/PainterOnline

#duoshuo name
duoshuo:

#disqus name
disqus_shortname:

#fancybox
fancybox: false

# Miscellaneous
github: https://github.com/MrKou47
weibo: http://weibo.com/

#about  timeline
timeline:
- num: 1
  word: 2014/06/12 - MIUI theme creator
- num: 2
  word: 2016/05/01 - FE
- num: 3
  word: Today - NOFE
- num: 4
  word: Feature - HUMAN
