# config
cover: /img/bg_img.jpg
logo: /img/logo.png
top_saying:
- title: YOU'VE MADE A <span>BRAVE</span> DECISION, WELCOME.
- content: 每一个不曾起舞的日子都是对生命的辜负。
bottom_saying: Lok’tar ogar
# Content
excerpt_link: Read More

rss: /atom.xml

highlightjs: vs

#Works
works:
- works_name: 微信小程序支付nodejs层接口
  works_url: https://github.com/MrKou47/wechatPay-node
- works_name: PainterOnline - use canvas
  works_url: https://github.com/MrKou47/PainterOnline

#duoshuo name
duoshuo:

#disqus name
disqus_shortname:

#fancybox
fancybox: false

# Miscellaneous
github: https://github.com/MrKou47
weibo: http://weibo.com/

#about  timeline
timeline:
- num: 1
  word: 2014/06/12 - Start
- num: 2
  word: 2016/05/01 - jquery x bootstrap x webApp
- num: 3
  word: Today - nodejs x react x typescript
- num: 4
  word: Feature - ?
